### ISSUE TITLE
Relations order 

### ISSUE THREAD

**Issue by kedarguy** [GraphCMS/Issue-tracker#65]
keep order and allow re-ordering of one to many / many to many relations.

Currently, when connecting a new relation, you cant control the order you will get them

**Comment by kedarguy** [comment]
Found a discussion on the slack channel about this...

**Comment by dendrochronology** [comment]
What did you find on this, @kedarguy? The only slack messages I found suggest adding a numerical index to the target model, but that won't work well for my current needs (modeling multiple "playlist" types, which can mash up any number of "track" types, many-to-many), because target tracks can show up in different places in any number of source playlists, in different order.

The system we're migrating from honored the order of relations (probably just tracked an internal index on the relation), so that the order in the drag-and-drop UI (as well as mutation inputs) was respected and preserved. Ordinals just worked, across the board. That system also supported repeatable fieldsets, which were handy if you needed to store more metadata about a relation (custom title, notes, etc.), but didn't want to pollute the wider model namespace.

My bar napkin sketch of workarounds for something like an audio playlist (playlist >-< track) is:

1. Create static 'slots' on the source side of the relation (e.g., playlist.track1, track2, track3)
2. Create an extra "wrapper" layer of relations to hold the ordinal index (Playlist <-< Playlist Track (index) >-< Track).

Option one is straight outta 1970's data modeling, and number 2 will get very messy as things scale (I will have _lots_ of extra models).
