### ISSUE TITLE
data dump?

### ISSUE THREAD

**Issue by tomByrer** [GraphCMS/Issue-tracker#7]
I'd like to know how to have an en-mass transfer of all records in & out of GraphCMS.  Handy for:
* backups
* transfer existing projects into GraphCMS
* re-use templates to set up new project
* reproduce tests

Maybe this is a request, or maybe exists & finding the steps could be improved?

**Comment by mlukaszczyk** [comment]
Hey @tomByrer, this is definitely something we need to document or write some tutorial for it. The great thing about APIs is that you are able to query or insert data however you like it. So if you want to implement some custom backup routine, you just need to write a script that will query your whole data graph and store it where ever you like.

Transfering existing projects into GraphCMS will take a little effort since you have to make sure that you create a data model on the GraphCMS side that will have the shape of the imported data. We have to elaborate if we can come up with some tooling here.

Content Model Templates:
This is something we will definitely implement in the next months. We understand that this is very important and we also want to create something like a content model template marketplace, so users could share content models (an ecommerce template, for example). This would also allow you to build a testing workflow. 

I assume that project cloning would also be something you are interested in?

Anyways, I will create some tickets related to this questions on our [roadmap](https://github.com/GraphCMS/Roadmap/projects/1) for march 🙏

**Comment by mlukaszczyk** [comment]
There we go:
https://github.com/GraphCMS/Roadmap/issues/10
https://github.com/GraphCMS/Roadmap/issues/11
https://github.com/GraphCMS/Roadmap/issues/12

We appreciate any thoughts and ideas you might have!

**Comment by mlukaszczyk** [comment]
Hey @tomByrer. There´s a small update here: https://github.com/GraphCMS/Roadmap/issues/10

**Comment by mlukaszczyk** [comment]
I will close this issue in favor to the roadmap tickets.
